### ISSUE TITLE
Confusion

### ISSUE THREAD

**Issue by ghost** [ClonkAndre/NativeUI-IV#1]
I have a doubt in my mind that, for example when we open Menu using the key and then we navigate using Arrow keys, does the game open up the phone when UpArrow key is pressed and same for other keys which do other stuff in-game like pressing 1 gives a melee weapon, pressing A rotate the player to Left, etc.

**Comment by ClonkAndre** [comment]
See the [NativeUI Wiki](https://github.com/ClonkAndre/NativeUI-IV/wiki/Getting-Started) under "Changing settings for all menus".

**Comment by ClonkAndre** [comment]
@its-SG Did the Wiki helped you? Or answered your question?

**Comment by ghost** [comment]
yeah i've understood
